baseurl: "https://batmat.net"
title: "batmat.net"
params:
  Description: "Blogounage"
  Id: "Bimbimbim"
languageCode: "fr-FR, en-US"
permalinks:
  post: /:year/:month/:day/:slug/
Author: "Baptiste Mathus"
Id: "hop"
